import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import { CLICK_ZONES } from "../src/click-zones";
import { createDefaultProfile } from "../src/default-profile";
import { BUILTIN_DRILLS, getRequiredActions, hotkeyStep } from "../src/drills";
import { actionsForStringIds, getHotkeyAction, HOTKEY_ACTIONS } from "../src/hotkey-actions";

describe("built-in drill", () => {
  it("allows more total time than all sequences at the Easy target", () => {
    const drill = BUILTIN_DRILLS[0];
    expect(drill?.totalTimeMs).toBe(137_000);
    expect(drill!.totalTimeMs).toBeGreaterThan(
      drill!.sequences.length * drill!.sequences[0]!.targetTimeMs[0],
    );
  });

  it("shows all twenty numbered click zones", () => {
    expect(CLICK_ZONES).toHaveLength(20);
    expect(CLICK_ZONES.map((zone) => zone.id)).toEqual(
      Array.from({ length: 20 }, (_, index) => index + 1),
    );
  });

  it("starts only the final four building sequences by selecting a villager", () => {
    const drill = BUILTIN_DRILLS[0];
    const simpleSequences = drill?.sequences.slice(0, -4) ?? [];
    const villagerSequences = drill?.sequences.slice(-4) ?? [];

    expect(simpleSequences.every((sequence) =>
      sequence.steps[0]?.type === "hotkey"
      && sequence.steps[0].action.startsWith("open_")
    )).toBe(true);
    expect(villagerSequences.map((sequence) => sequence.name)).toEqual([
      "Stable",
      "Stone Wall",
      "Town Center",
      "University",
    ]);
    expect(villagerSequences.every((sequence) =>
      sequence.steps[0]?.type === "hotkey" && sequence.steps[0].action === "select_villager"
    )).toBe(true);
  });

  it("provides the complete named action catalogue and common selection actions", () => {
    expect(HOTKEY_ACTIONS.size).toBeGreaterThanOrEqual(500);
    expect(getHotkeyAction("select_all_stables")).toMatchObject({ stringId: 19016 });
    expect(getHotkeyAction("select_all_town_centers")).toMatchObject({ stringId: 19021 });
  });

  it("supports dynamic numeric action IDs and rejects malformed IDs", () => {
    expect(getHotkeyAction("hotkey_999999")).toEqual({
      id: "hotkey_999999",
      label: "Hotkey action 999999",
      stringId: 999999,
    });
    expect(getHotkeyAction("not-an-action")).toBeUndefined();
    expect(getHotkeyAction("hotkey_0")).toBeUndefined();
    expect(getHotkeyAction("hotkey_999999999999999999999")).toBeUndefined();

    const actions = actionsForStringIds([999999, 999999, 1]);
    expect(actions.filter((action) => action.stringId === 999999)).toHaveLength(1);
  });

  it("deduplicates required actions and ignores unsupported IDs", () => {
    const drill = {
      id: "requirements",
      name: "Requirements",
      description: "Test",
      totalTimeMs: 1000,
      sequences: [{
        id: "one",
        name: "One",
        targetTimeMs: [1, 1, 1, 1, 1, 1, 1] as const,
        steps: [
          { type: "hotkey" as const, action: "select_villager", label: "Select", onFailure: "wait" as const },
          { type: "hotkey" as const, action: "select_villager", label: "Select", onFailure: "wait" as const },
          { type: "hotkey" as const, action: "invalid", label: "Invalid", onFailure: "wait" as const },
          { type: "click" as const, zone: 1, label: "Click", onFailure: "wait" as const },
        ],
      }],
    };
    expect(getRequiredActions(drill).map((action) => action.id)).toEqual(["select_villager"]);
    expect(() => hotkeyStep("invalid", "wait")).toThrow("Unknown hotkey action");
  });

  it("uses current installed-game labels for newer profile actions", () => {
    const actions = actionsForStringIds([419232]);
    expect(actions).toContainEqual({
      id: "hotkey_419232",
      label: "Scenario 13: Hire Cavalry",
      stringId: 419232,
    });
    expect(actions.length).toBeGreaterThanOrEqual(630);
  });

  it("loads the complete reset default profile instead of a small manual subset", () => {
    const profile = createDefaultProfile();
    const actions = actionsForStringIds(profile.bindings.keys());

    expect(profile.bindings.size).toBeGreaterThan(600);
    expect(actions.length).toBeGreaterThan(600);
    expect(profile.bindings.get(19021)).toBeDefined();
  });

  it("stores only generated functional bindings, not embedded profile binaries", () => {
    const source = readFileSync("src/default-profile.ts", "utf8");

    expect(source).toContain("Generated by npm run generate:default-profile");
    expect(source).not.toMatch(/\b(?:BASE|HOTKEYS)_HKP\b|atob\s*\(/);
    expect(source).not.toMatch(/[A-Za-z0-9+/]{200,}={0,2}/);
  });
});
