import { getHotkeyAction } from "./hotkey-actions";

export interface BuiltinCommandPanelEntry {
  action: string;
  label: string;
  slot: number;
}

export interface BuiltinCommandPanelDefinition {
  asset: string;
  description: string;
  drillId: string;
  entries: readonly BuiltinCommandPanelEntry[];
  id: string;
  name: string;
  visualAlternatives?: readonly {
    reason: string;
    slot: number;
  }[];
}

function entry(action: string, slot: number, label?: string): BuiltinCommandPanelEntry {
  return { action, label: label ?? getHotkeyAction(action)!.label, slot };
}

export const BUILTIN_COMMAND_PANELS: readonly BuiltinCommandPanelDefinition[] = [
  {
    asset: "mill-panel.png",
    description: "Practice the farm-management and farming-upgrade commands shown when a Mill is selected.",
    drillId: "mill-commands",
    entries: [entry("hotkey_19337", 0), entry("hotkey_19074", 3), entry("hotkey_19100", 4)],
    id: "mill",
    name: "Mill Commands",
  },
  {
    asset: "mining-camp-panel.png",
    description: "Practice the resource-upgrade commands shown when a Mining Camp is selected.",
    drillId: "mining-camp-commands",
    entries: [entry("hotkey_19338", 0), entry("hotkey_19339", 1)],
    id: "mining-camp",
    name: "Mining Camp Commands",
  },
  {
    asset: "lumber-camp-panel.png",
    description: "Practice the wood-upgrade command shown when a Lumber Camp is selected.",
    drillId: "lumber-camp-commands",
    entries: [entry("hotkey_19340", 0)],
    id: "lumber-camp",
    name: "Lumber Camp Commands",
  },
  {
    asset: "gate-panel.png",
    description: "Practice locking, unlocking, and rotating Gates.",
    drillId: "gate-commands",
    entries: [
      entry("hotkey_19122", 0),
      entry("hotkey_19331", 0),
      entry("hotkey_19332", 0),
    ],
    id: "gate",
    name: "Gate Commands",
  },
  {
    asset: "blacksmith-panel.png",
    description: "Practice the attack and armor upgrades shown when a Blacksmith is selected.",
    drillId: "blacksmith-commands",
    entries: [
      entry("hotkey_19470", 0),
      entry("hotkey_19471", 1),
      entry("hotkey_19472", 2),
      entry("hotkey_19473", 5),
      entry("hotkey_19474", 6),
    ],
    id: "blacksmith",
    name: "Blacksmith Commands",
  },
  {
    asset: "market-panel.png",
    description: "Practice trade, economic technologies, and resource exchange commands shown at the Market.",
    drillId: "market-commands",
    entries: [
      entry("hotkey_19286", 0),
      entry("hotkey_19348", 1),
      entry("hotkey_19349", 2),
      entry("hotkey_19450", 3),
      entry("hotkey_419057", 4),
      entry("hotkey_19103", 6),
      entry("hotkey_19102", 7),
      entry("hotkey_19104", 8),
      entry("hotkey_19112", 11),
      entry("hotkey_19111", 12),
      entry("hotkey_19113", 13),
    ],
    id: "market",
    name: "Market Commands",
  },
  {
    asset: "university-panel.png",
    description: "Practice the shared technology commands shown when a University is selected.",
    drillId: "university-commands",
    entries: [
      entry("hotkey_19488", 0),
      entry("hotkey_19489", 1),
      entry("hotkey_19490", 2),
      entry("hotkey_19491", 3),
      entry("hotkey_19492", 4),
      entry("hotkey_19493", 5),
      entry("hotkey_19495", 6),
      entry("hotkey_19497", 7),
      entry("hotkey_19496", 8),
      entry("hotkey_19494", 9),
      entry("hotkey_19342", 10),
      entry("hotkey_19356", 11),
      entry("hotkey_19343", 12),
      entry("hotkey_19357", 13),
    ],
    id: "university",
    name: "University Commands",
  },
  {
    asset: "monastery-panel.png",
    description: "Practice Monk creation and the shared technologies shown when a Monastery is selected.",
    drillId: "monastery-commands",
    entries: [
      entry("hotkey_19051", 0),
      entry("hotkey_19478", 1),
      entry("hotkey_19479", 2),
      entry("hotkey_19480", 3),
      entry("hotkey_19002", 4),
      entry("hotkey_19481", 5),
      entry("hotkey_19482", 6),
      entry("hotkey_19483", 7),
      entry("hotkey_19484", 8),
      entry("hotkey_19485", 10),
      entry("hotkey_19486", 11),
      entry("hotkey_19487", 12),
    ],
    id: "monastery",
    name: "Monastery Commands",
  },
  {
    asset: "dock-panel.png",
    description: "Practice the representative ship, naval technology, and utility commands shown at the Dock.",
    drillId: "dock-commands",
    entries: [
      entry("hotkey_19045", 0),
      entry("hotkey_19059", 1),
      entry("hotkey_19053", 2),
      entry("hotkey_19279", 3),
      entry("hotkey_19002", 4),
      entry("hotkey_19284", 5),
      entry("hotkey_19044", 6),
      entry("hotkey_19280", 7),
      entry("hotkey_19055", 8),
      entry("hotkey_19341", 10),
      entry("hotkey_19342", 11),
      entry("hotkey_19343", 12),
      entry("hotkey_19347", 13),
      entry("hotkey_19358", 14),
    ],
    id: "dock",
    name: "Dock Commands",
  },
  {
    asset: "barracks-panel.png",
    description: "Practice representative unit-production and upgrade commands shown at the Barracks.",
    drillId: "barracks-commands",
    entries: [
      entry("hotkey_19035", 0),
      entry("hotkey_19034", 1),
      entry("hotkey_19070", 3),
      entry("hotkey_19002", 4),
      entry("hotkey_19451", 5),
      entry("hotkey_19452", 6),
      entry("hotkey_19453", 8),
      entry("hotkey_19454", 10),
      entry("hotkey_19455", 11),
      entry("hotkey_19456", 12),
      entry("hotkey_19217", 14),
    ],
    id: "barracks",
    name: "Barracks Commands",
  },
  {
    asset: "archery-range-panel.png",
    description: "Practice representative unit-production and upgrade commands shown at the Archery Range.",
    drillId: "archery-range-commands",
    entries: [
      entry("hotkey_19038", 0),
      entry("hotkey_19043", 1),
      entry("hotkey_19040", 2),
      entry("hotkey_19041", 3),
      entry("hotkey_19002", 4),
      entry("hotkey_19458", 5),
      entry("hotkey_19459", 6),
      entry("hotkey_19460", 7),
      entry("hotkey_19145", 8),
      entry("hotkey_19461", 10),
      entry("hotkey_19149", 11),
      entry("hotkey_19462", 12),
      entry("hotkey_19463", 13),
    ],
    id: "archery-range",
    name: "Archery Range Commands",
  },
  {
    asset: "stable-panel.png",
    description: "Practice representative unit-production and upgrade commands shown at the Stable.",
    drillId: "stable-commands",
    entries: [
      entry("hotkey_19060", 0),
      entry("hotkey_19030", 1),
      entry("hotkey_19031", 2),
      entry("hotkey_19033", 3),
      entry("hotkey_19002", 4),
      entry("hotkey_19464", 5),
      entry("hotkey_19465", 6),
      entry("hotkey_19466", 7),
      entry("hotkey_19467", 8),
      entry("hotkey_19468", 10),
      entry("hotkey_19469", 11),
      entry("hotkey_19217", 14),
    ],
    id: "stable",
    name: "Stable Commands",
  },
  {
    asset: "siege-workshop-panel.png",
    description: "Practice representative siege production and upgrade commands shown at the Siege Workshop.",
    drillId: "siege-workshop-commands",
    entries: [
      entry("hotkey_19056", 0),
      entry("hotkey_19285", 1),
      entry("hotkey_19049", 2),
      entry("hotkey_19047", 11, "Traction Trebuchet"),
      entry("hotkey_19002", 4),
      entry("hotkey_19475", 5),
      entry("hotkey_19476", 6),
      entry("hotkey_19477", 7),
      entry("hotkey_19048", 13),
      entry("hotkey_19217", 14),
    ],
    id: "siege-workshop",
    name: "Siege Workshop Commands",
    visualAlternatives: [{
      reason: "Bombard Cannon shares hotkey action 19047; Traction Trebuchet is the chosen drill representative.",
      slot: 3,
    }],
  },
  {
    asset: "town-center-panel.png",
    description: "Practice Villager creation and the shared commands shown when a Town Center is selected.",
    drillId: "town-center-commands",
    entries: [
      entry("train_villager", 0),
      entry("hotkey_19002", 4),
      entry("hotkey_19333", 5),
      entry("hotkey_19334", 6),
      entry("hotkey_19335", 7),
      entry("hotkey_19336", 10),
      entry("hotkey_19324", 13),
      entry("hotkey_19319", 14),
    ],
    id: "town-center",
    name: "Town Center Commands",
  },
  {
    asset: "castle-panel.png",
    description: "Practice representative unit, technology, and utility commands shown when a Castle is selected.",
    drillId: "castle-commands",
    entries: [
      entry("hotkey_19322", 0),
      entry("hotkey_19321", 1),
      entry("hotkey_19069", 2),
      entry("hotkey_19002", 4),
      entry("hotkey_19080", 5),
      entry("hotkey_19081", 6),
      entry("hotkey_19082", 7),
      entry("hotkey_19083", 10),
      entry("hotkey_19084", 11),
      entry("hotkey_19085", 12),
      entry("hotkey_19086", 13),
    ],
    id: "castle",
    name: "Castle Commands",
  },
  {
    asset: "military-unit-panel.png",
    description: "Practice the shared movement, stance, and formation commands used by infantry, archers, and cavalry.",
    drillId: "military-unit-commands",
    entries: [
      entry("hotkey_19312", 0),
      entry("hotkey_19313", 1),
      entry("hotkey_19314", 2),
      entry("hotkey_200008", 3),
      entry("hotkey_400017", 4),
      entry("hotkey_19315", 5),
      entry("hotkey_19316", 6),
      entry("hotkey_19317", 7),
      entry("hotkey_19318", 8),
      entry("hotkey_19304", 10),
      entry("hotkey_19303", 11),
      entry("hotkey_19305", 12),
      entry("hotkey_19306", 13),
    ],
    id: "military-unit",
    name: "Infantry, Archer & Cavalry Commands",
  },
  {
    asset: "siege-unit-panel.png",
    description: "Practice the shared movement, stance, and attack-ground commands used by siege units.",
    drillId: "siege-unit-commands",
    entries: [
      entry("hotkey_19312", 0),
      entry("hotkey_19313", 1),
      entry("hotkey_19314", 2),
      entry("hotkey_200008", 3),
      entry("hotkey_19220", 4),
      entry("hotkey_19315", 5),
      entry("hotkey_19316", 6),
      entry("hotkey_19317", 7),
      entry("hotkey_19318", 8),
    ],
    id: "siege-unit",
    name: "Siege Unit Commands",
  },
  {
    asset: "fishing-ship-panel.png",
    description: "Practice the useful commands shown when a Fishing Ship is selected.",
    drillId: "fishing-ship-commands",
    entries: [
      entry("hotkey_19202", 0),
      entry("hotkey_400021", 4),
      entry("hotkey_400017", 8),
      entry("hotkey_19216", 9),
      entry("hotkey_19123", 10),
      entry("hotkey_19101", 11),
    ],
    id: "fishing-ship",
    name: "Fishing Ship Commands",
  },
  {
    asset: "trade-cog-panel.png",
    description: "Practice changing the resource ratio used by a Trade Cog.",
    drillId: "trade-cog-commands",
    entries: [entry("hotkey_419057", 2)],
    id: "trade-cog",
    name: "Trade Cog Commands",
    visualAlternatives: [
      {
        reason: "The local game hotkey data exposes one Toggle Trading Ratio action for the three resource-ratio images.",
        slot: 0,
      },
      {
        reason: "The local game hotkey data exposes one Toggle Trading Ratio action for the three resource-ratio images.",
        slot: 1,
      },
    ],
  },
  {
    asset: "transport-ship-panel.png",
    description: "Practice unloading and stopping a Transport Ship.",
    drillId: "transport-ship-commands",
    entries: [
      entry("hotkey_19225", 0),
      entry("hotkey_19216", 9),
    ],
    id: "transport-ship",
    name: "Transport Ship Commands",
  },
  {
    asset: "monk-unit-panel.png",
    description: "Practice representative Monk commands using the captured group-of-Monks command panel.",
    drillId: "monk-unit-commands",
    entries: [
      entry("hotkey_19222", 0),
      entry("hotkey_19221", 1),
      entry("hotkey_19314", 2),
      entry("hotkey_400017", 4),
      entry("hotkey_19304", 10),
      entry("hotkey_19303", 11),
      entry("hotkey_19305", 12),
      entry("hotkey_19306", 13),
    ],
    id: "monk-unit",
    name: "Monk Commands",
  },
  {
    asset: "trebuchet-unit-panel.png",
    description: "Practice unpacking and shared group commands using the captured packed-Trebuchet command panel.",
    drillId: "trebuchet-unit-commands",
    entries: [
      entry("hotkey_19242", 0),
      entry("hotkey_200008", 5),
      entry("hotkey_19317", 8),
      entry("hotkey_19304", 10),
      entry("hotkey_19303", 11),
      entry("hotkey_19305", 12),
      entry("hotkey_19306", 13),
    ],
    id: "trebuchet-unit",
    name: "Trebuchet Commands",
  },
];

export const BUILTIN_COMMAND_PANEL_BY_ID = new Map(
  BUILTIN_COMMAND_PANELS.map((panel) => [panel.id, panel]),
);
